### PR TITLE
Date edited, Logo and boxbilling references

### PR DESCRIPTION
**Pull request by OnlyHardOfficial**
Guys! I hope to help you some more!

- content.sql -->Changed all dates to the date:2018-06-05 and all correspondence concerning "boxbilling"-->"circleBilling" e "BoxBilling"---->"CircleBilling"

- content_test.sql-->Iall dates for the date::2018-06-05 and all correspondence concerning "boxbilling"-->"circleBilling" e "BoxBilling"---->"CircleBilling".

- structure.sql -->Line 969 I am not sure if I can change without consequences but I change two correspondences safely and also the dates all for the date: 2018-06-05 and all related correspondences from "boxbilling"-->"circleBilling" e "BoxBilling"---->"CircleBilling"

### CODE REVIEW

**Comment by Eiskaltereistee** [comment]
@OnlyHardOfficial where did you get the icons from?

Also please remove the logo, we will add that later.

Thank you.

**Comment by OnlyHardOfficial** [comment]
I got it as a global image of the internet, but it was only a test to improve the configuration even if these extensions were with the broken images or without image "icon.png"
OK reversed! I'll let you know when you're ready.
But anyway I'll show here the copyright images of BBilling, which they used in their icons, images of extensions etc ...

**Comment by OnlyHardOfficial** [comment]
I'm not quite understanding this here! I made the changes but something says it is not right

https://travis-ci.org/CircleBilling/CircleBilling/builds/388055358?utm_source=github_status&utm_medium=notification

**Comment by OnlyHardOfficial** [comment]
a mi progresses here https://i.gyazo.com/9e437faa0f67810e2b6465d883320ac1.jpg

**Comment by StefvanEgmond** [comment]
This is not what @Eiskaltereistee asked for. Please consider reading his comment.

By the way, we disallow bitly url.

**Comment by OnlyHardOfficial** [comment]
But why!? Does not make the code more structured?

**Pull request closed without merging**
